CREATE TABLE `ai_device_proactive_preference` (
    `device_id` varchar(32) NOT NULL COMMENT 'ai_device.id',
    `mac_address` varchar(50) NOT NULL COMMENT '设备MAC地址',
    `mode` varchar(24) NOT NULL DEFAULT 'AGGRESSIVE',
    `daily_limit` int NOT NULL DEFAULT 5,
    `quiet_start` time DEFAULT NULL,
    `quiet_end` time DEFAULT NULL,
    `allowed_topics` json NOT NULL,
    `blocked_topics` json NOT NULL,
    `previous_mode` varchar(24) DEFAULT NULL COMMENT 'today silent前的模式',
    `silent_until` datetime DEFAULT NULL COMMENT '次日服务端恢复时间',
    `version` int NOT NULL DEFAULT 0,
    `created_at` datetime NOT NULL,
    `updated_at` datetime NOT NULL,
    PRIMARY KEY (`device_id`),
    UNIQUE KEY `uk_ai_device_proactive_preference_mac` (`mac_address`),
    CONSTRAINT `fk_proactive_preference_device` FOREIGN KEY (`device_id`) REFERENCES `ai_device` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备主动助理偏好';

CREATE TABLE `ai_device_proactive_event` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT,
    `device_id` varchar(32) NOT NULL COMMENT 'ai_device.id',
    `mac_address` varchar(50) NOT NULL COMMENT '设备MAC地址',
    `event_id` varchar(64) NOT NULL,
    `topic` varchar(32) NOT NULL,
    `priority` varchar(16) NOT NULL,
    `reason` varchar(255) NOT NULL,
    `event_type` varchar(32) NOT NULL,
    `payload` json NOT NULL,
    `created_at` datetime NOT NULL,
    `expires_at` datetime DEFAULT NULL,
    `dedupe_key` varchar(128) NOT NULL,
    `requires_response` tinyint(1) NOT NULL DEFAULT 0,
    `delivery_status` varchar(24) NOT NULL DEFAULT 'PENDING',
    `outcome` varchar(24) NOT NULL DEFAULT 'NONE',
    `delivered_at` datetime DEFAULT NULL,
    `updated_at` datetime NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_device_proactive_event_id` (`event_id`),
    UNIQUE KEY `uk_ai_device_proactive_event_dedupe` (`device_id`, `dedupe_key`),
    KEY `idx_ai_device_proactive_event_page` (`device_id`, `created_at`, `id`),
    CONSTRAINT `fk_proactive_event_device` FOREIGN KEY (`device_id`) REFERENCES `ai_device` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='主动助理事件审计';

CREATE TABLE `ai_device_proactive_habit` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT,
    `device_id` varchar(32) NOT NULL COMMENT 'ai_device.id',
    `mac_address` varchar(50) NOT NULL COMMENT '设备MAC地址',
    `habit_type` varchar(32) NOT NULL,
    `habit_key` varchar(128) NOT NULL,
    `evidence_count` int unsigned NOT NULL DEFAULT 1,
    `first_seen_at` datetime NOT NULL,
    `last_seen_at` datetime NOT NULL,
    `suggested` tinyint(1) NOT NULL DEFAULT 0,
    `accepted` tinyint(1) NOT NULL DEFAULT 0,
    `dismissed` tinyint(1) NOT NULL DEFAULT 0,
    `payload` json NOT NULL,
    `created_at` datetime NOT NULL,
    `updated_at` datetime NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_device_proactive_habit` (`device_id`, `habit_type`, `habit_key`),
    KEY `idx_ai_device_proactive_habit_candidates` (`device_id`, `suggested`, `dismissed`, `last_seen_at`),
    CONSTRAINT `fk_proactive_habit_device` FOREIGN KEY (`device_id`) REFERENCES `ai_device` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='主动助理习惯候选';
